services:
  backend:
    container_name: physagent-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - physagent-network

  frontend:
    container_name: physagent-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - physagent-network
    
networks:
  physagent-network:
    name: physagent-network