[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "langchain-core>=0.3.34",
    "langchain-groq>=0.2.4",
    "langgraph>=0.2.70",
    "pydantic-settings>=2.7.1",
    "pydantic>=2.10.6",
    "langchain-mongodb>=0.7.0",
    "langchain-text-splitters>=0.3.9",
    "langchain-huggingface>=0.3.1",
    "langchain-community>=0.3.29",
    "transformers>=4.56.1",
    "datasketch>=1.6.5",
]
